protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
    function init()
    {
        $this->layout = 'main';
    }

    public function actionBuySubs()
    {
        if (!Yii::app()->user->isGuest) {
            $type = Yii::app()->getRequest()->getParam('type');
            if ($type != '') {
                $price = Price::model()->find();

                $user = User::model()->findByPk(Yii::app()->user->id);
                $datePay = $user->datePay;
                if ($datePay < date('Y-m-d H:i:s')) $datePay = date('Y-m-d H:i:s');

                $pay = new Pay;
                $pay->date = date('Y-m-d H:i:s');
                $pay->type = 0;
                $pay->type_pay = 5;
                $pay->user_id = Yii::app()->user->id;

                if ($type == 1) {
                    if ($user->userBalance < $price->testPrice) {
                        Yii::app()->user->setFlash('danger', 'На Вашем балансе недостаточно денежных средств!');
                        $this->redirect(Yii::app()->getRequest()->getBaseUrl(true) . '/payment');
                    }

                    if ($user->test) {
                        Yii::app()->user->setFlash('danger', 'Тестовый период недоступен!');
                        $this->redirect(Yii::app()->getRequest()->getBaseUrl(true) . '/payment');
                    }

                    $pay->sum = $price->testPrice;

                    $user->datePay = date('Y-m-d H:i:s', strtotime($datePay . ' +1 day'));
                    $user->typeSubs = 1;
                    $user->test = 1;
                    $user->userBalance -= $price->testPrice;

                    if ($user->save() && $pay->save()) {
                        Yii::app()->user->setFlash('success', 'Тестовый период успешно активирован!');
                        $this->redirect(Yii::app()->getRequest()->getBaseUrl(true) . '/payment');
                    }
                } elseif ($type == 2) {
                    if ($user->userBalance < $price->mounthPrice) {
                        Yii::app()->user->setFlash('danger', 'На Вашем балансе недостаточно денежных средств!');
                        $this->redirect(Yii::app()->getRequest()->getBaseUrl(true) . '/payment');
                    }

                    $pay->sum = $price->mounthPrice;

                    $user->datePay = date('Y-m-d H:i:s', strtotime($datePay . ' +31 day'));
                    $user->typeSubs = 1;
                    $user->test = 1;
                    $user->userBalance -= $price->mounthPrice;

                    if ($user->save() && $pay->save()) {
                        Yii::app()->user->setFlash('success', 'Подписка на 1 месяц успешно активирована!');
                        $this->redirect(Yii::app()->getRequest()->getBaseUrl(true) . '/payment');
                    }
                }
            }
        } else $this->redirect(Yii::app()->getRequest()->getBaseUrl(true));
    }

    public function actionStat()
    {
        $id = Yii::app()->getRequest()->getParam('album_id');
        $id = explode(',', $id);
        $settings = Settings::model()->find('idUser = :id', array(':id' => Yii::app()->user->id));
        $criteria = new CDbCriteria;
        $criteria->select = 'totalPhoto, COUNT(*) AS currentPhoto';
        $criteria->condition = 'idSettings = :id AND idAlbum = :aid';
        $criteria->group = 'photoWall';
        $result = array();
        for ($i = 0; $i < count($id); $i++) {
            $criteria->params = array(':id' => $settings->idSettings, ':aid' => $id[$i]);
            $wall = Wall::model()->findAll($criteria);
            $result[$id[$i]]['total'] = 0;
            $result[$id[$i]]['current'] = 0;
            $result[$id[$i]]['comment'] = 0;
            if (count($wall)) {
                if ($wall[0]->totalPhoto != null)
                    $result[$id[$i]]['total'] = (int)$wall[0]->totalPhoto;
                $result[$id[$i]]['current'] = (int)count($wall);
                foreach ($wall as $key => $value) {
                    $result[$id[$i]]['comment'] += $value['currentPhoto'];
                }
            }
        }
        $result = json_encode($result);
        echo $result;
    }

    public function actionIndex()
    {
        if (Yii::app()->user->isGuest) {
            $this->layout = 'index';
            $this->render('index');
        } else {

            if (Yii::app()->request->isAjaxRequest) {

                $model = Settings::model()->find('idUser=:myParams', array(':myParams' => Yii::app()->user->id));
                if (Count($model) == 1) {

                    $this->performAjaxValidation($model, 'user-form');
                    if (isset($_POST['Settings'])) {
                        $model->attributes = $_POST['Settings'];
                        if ($model->nameCity == '') {
                            $model->idCity = NULL;
                        }
                        //die (var_dump($model));
                        if ($model->save()) {
                            echo('Данные сохранены');
                        }

                    }

                } else {
                    $model = new Settings;

                    $this->performAjaxValidation($model, 'user-form');
                    if (isset($_POST['Settings'])) {
                        $model->attributes = $_POST['Settings'];
                        if ($model->nameCity == '') {
                            $model->idCity = 0;
                        }

                        if ($model->save()) {
                            echo('Данные сохранены');
                        }
                    }
                }
            } else {

                $model = Settings::model()->find('idUser=:myParams', array(':myParams' => Yii::app()->user->id));
                if (Count($model) == 0) {
                    $model = new Settings;
                } else {
                    if ($model->dateFrom == '0000-00-00') {
                        $model->dateFrom = '';
                    }
                    if ($model->dateTo == '0000-00-00') {
                        $model->dateTo = '';
                    }
                    //die(var_dump($model));
                    if ($model->idCity != 0) {
                        $response = SendHelper::send('https://api.vk.com/method/database.getCitiesById?lang=ru&city_ids=' . $model->idCity);
                        preg_match('/name":"(.*?)"}/', $response, $matches);
                        $model->nameCity = $matches[1];
                    } else {
                        $model->nameCity = '';
                    }
                }
                $response = SendHelper::send('https://api.vk.com/method/database.getCountries?lang=ru&need_all=1&count=234', "", "", "", true);
                preg_match_all('/"cid":(.*?),"title":"(.*?)"/', $response, $matches);
                $country = array_combine($matches[1], $matches[2]);
                ///$resul = Wall::model()->findAll();
                $dataProvider = new CActiveDataProvider('Wall', array(
                    'criteria' => array(
                        'condition' => 't.tipeText=0',
                        'order' => 'idWall DESC',
                        'with' => array(
                            'Settings' => array(
                                'condition' => 'Settings.idUser=:id',
                                'params' => array(
                                    ':id' => Yii::app()->user->id))))));
                $response = Settings::model()->find('idUser = :id', array(':id' => Yii::app()->user->id));
                if (count($response) > 0) {
                    $pid = $response->Pid;
                    $labelMax = $response->countWall;
                    $labelNow = $response->nowCount;
                } else {
                    $pid = '';
                    $labelMax = '0';
                    $labelNow = '0';
                }
                $res = Wall::model()->with(array('Settings' => array('condition' => 'Settings.idUser=:id', 'params' => array(':id' => Yii::app()->user->id))))->findAll('tipeText=0');

                $countAll = count($res);

                $urlTxt = $response->nameTxt;
                $urlXls = $response->nameXls;
                $groupRes = Wall::model()->with(array('Settings' => array('condition' => 'Settings.idUser=:id', 'params' => array(':id' => Yii::app()->user->id))))->findAll('tipeText=0');


                $group = new UserGroup;

                $this->render('cabinet', array('country' => $country, 'countAll' => $countAll, 'groupRes' => $groupRes, 'labelMax' => $labelMax, 'labelNow' => $labelNow, 'urlXls' => $urlXls, 'urlTxt' => $urlTxt, 'group' => $group, 'pid' => $pid, 'model' => $model, 'resul' => $dataProvider));


            }
        }
        $pars = Yii::app()->getRequest()->getParam('pars');

    }

    protected function performAjaxValidation($model, $form)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === $form) {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    public function actionLogin()
    {

        $code = Yii::app()->request->getParam('code');
        $response = SendHelper::send('https://oauth.vk.com/access_token?client_id=' .
            Yii::app()->params['vk_application_id'] . '&client_secret=' . Yii::app()->params['vk_client_secret'] . '&code=' . $code . '&redirect_uri=' .
            Yii::app()->request->getBaseUrl(true) . '/site/login', '', '', '', true);
        $response = json_decode($response, 1);
        if (isset($response['access_token'])) {
            $token = $response['access_token'];
            $id = $response['user_id'];
            Yii::app()->session['urlPhoto'] = User::avatar($id);

            if ($token != '') {

                $response = SendHelper::send('https://api.vk.com/method/users.get?user_ids=' . $id, '', '', '', true);
                $response = json_decode($response, 1);

protected/views/site/_Wall.php
<div class="row" id="post"> 
<div class="col-md-2 col-sm-2"></div> 
<div class="col-md-8 col-sm-8">
<div class="panel panel-default">
<div class="panel-heading"><a href="https://vk.com/id<?echo $data->idUser?>">https://vk.com/id<?echo $data->idUser?></a><i id="id" style="cursor:pointer" class="pull-right checkstyle" onClick="checkPost(>)"><?echo $data->dataWall?></i><div class="field-field-recommended-url"><p class="editTextareap" onClick=></p></div>
</div>
<div class="panel-body"><?echo $data->textWall?>
<img width="100%" height="100%" src="<?echo $data->photoWall?>">
</div>

</div>
</div>
</div>

protected/views/site/_group.php
<div class="col-md-12 panel panel-default padding">
    <div class="col-md-2 col-xs-12">
        <input class="album-checkbox" type="checkbox" name="news[]" value="<?= $data['id'] ?>" id="<?= $data['id'] ?>">
        <label for="<?= $data['id'] ?>"><img src="<?= $data['image'] ?>" alt="..."></label>
    </div>
    <div class="col-md-9 col-xs-12 col-md-offset-1">
        <label>Альбом: </label> <a href="site/SelectGroup?aid=<?= $data['id'] ?>&url=<?= $url ?>"><?= $data['title'] ?></a><br>
        <label>Получено комментариев: </label> <span id="countComment<?= $data['id'] ?>"></span><br>
        <label>Ход выполнения</label>

        <div class="progress progress-striped active">
            <div class="progress-bar" role="progressbar" data-id="<?= $data['id'] ?>" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <a class="btn btn-primary offset col-md-5" name="xls" target="_blank" href="site/exportAlbum?type=txt&id=<?= $data['id'] ?>">.xls</a>
        <a class="btn btn-primary offset col-md-5 col-md-offset-2" name="txt" target="_blank" href="site/exportAlbum?type=xls&id=<?= $data['id'] ?>">.txt</a>
    </div>
    <div class="clearfix"></div>
</div>

protected/views/site/_selectgroup.php
<div class="panel panel-default padding <?= $color[$data['tipeSelect']] ?>">
    <div class="row">
        <div class="col-md-2 col-xs-6">
            <input type="checkbox" name="news[]" class="album-checkbox" value="<?= $data['idWall'] ?>" id="<?= $data['idWall'] ?>">
            <? if (!empty($data['photoWall'])) { ?>
                <label for="<?= $data['idWall'] ?>"><img src="<?= $data['photoWall'] ?>" alt="..." width="200px"></label>
            <? } ?>
        </div>
        <div class="col-md-3 col-xs-6 col-md-offset-1">
            <label>Дата: </label> <?= $data['dataWall'] ?><br>
            <label>Пользователь:</label> <a href="https://vk.com/id<?= $data['idUser'] ?>"><?= $data['nameAlbum'] ?></a><br>
        </div>
        <div class="col-md-6 col-xs-12">
            <?= $data['textWall'] ?>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

protected/views/site/_selectwall.php
<div class="panel panel-info">
	<div class="row">
        <div class="col-md-2">
		<img src="<?echo $data['photo']?>" alt="...">
 		</div>
 		<center>Альбом:<?echo $data['nameAlbum']?></center>
 		<div style='float: right'><?echo $data['date']?></div>
 		<a href="https://vk.com/id<?echo $data['user']?>"><?echo $data['name']?></a><br>
 		<?echo $data['text']?>
 	</div>
</div>

protected/views/site/_table.php
<div class="col-md-12 panel panel-default padding">
    <div class="col-md-2 col-xs-6">
        <img src="<?= $data['photo'] ?>" alt="...">
    </div>
    <div class="col-md-3 col-xs-6 col-md-offset-1">
        <label>Альбом:</label> <?= $data['nameAlbum'] ?><br>
        <label>Дата:</label> <?= $data['date'] ?><br>
        <label>Автор:</label> <a href="https://vk.com/id<?= $data['user'] ?>"><?= $data['name'] ?></a>
    </div>
    <div class="col-md-6 col-xs-12">
        <?= $data['text'] ?>
    </div>
    <div class="clearfix"></div>
</div>

protected/views/site/fail.php
<?php
echo 'Ошибка!';

protected/views/site/groups.php
<div class="col-md-12">
    <h2>Альбомы группы <?= $nameGroup ?></h2>
    <!--    <h5>В этом разделе вы можете выбрать удобный для Вас способ пополнения баланса</h5>-->
    <hr>
    <? $this->widget('zii.widgets.CBreadcrumbs', array(
        'htmlOptions' => array(
            'class' => 'breadcrumb'
        ),
        'homeLink' => '<a href="' . Yii::app()->getRequest()->getBaseUrl(true) . '">Главная</a>',
        'links' => array(
            'Альбомы группы ' . $nameGroup,
        ),
    )); ?>
</div>
</div>

<? if (Yii::app()->user->hasFlash('name')) {
    echo Yii::app()->user->getFlash('name');
} ?>

<? $form = $this->beginWidget('CActiveForm', array(
    'action' => 'site/group',
    'id' => 'group',
    'method' => 'post'
)) ?>
<div class="row">
    <div class="col-md-12">
        <?= CHtml::hiddenField('url', $url) ?>
        <div class="col-xs-12 col-md-6 panel panel-primary">
            <div class="col-md-12 form-group padding-top">
                <?= $form->checkBox($model, 'postImg') ?>
                <?= $form->labelEx($model, 'postImg') ?>
            </div>
            <div class="col-md-6 form-group">
                <label for="dateFrom">Дата с</label>
                <?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                    'name' => 'DateWallFrom',
                    'model' => $model,
                    'attribute' => 'DateWallFrom',
                    'language' => 'ru',
                    'options' => array(
                        'dateFormat' => 'yy-mm-dd',
                        'showAnim' => 'fold',
                    ),
                    'htmlOptions' => array(
                        'class' => 'form-control',
                    ),
                ));?>
            </div>
            <div class="col-md-6 form-group">
                <label for="dateTo">Дата по</label>
                <?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                    'name' => 'DateWallTo',
                    'attribute' => 'DateWallTo',
                    'model' => $model,
                    'language' => 'ru',
                    'options' => array(
                        'dateFormat' => 'yy-mm-dd',
                        'class' => 'form-control',
                        'showAnim' => 'fold',
                    ),
                    'htmlOptions' => array(
                        'class' => 'form-control',
                    ),
                )); ?>
            </div>
            <div class="col-md-6 form-group">
                <button class="search btn btn-primary form-control" name="but" type="submit" value="1">Старт</button>
            </div>
            <div class="col-md-6 form-group">
                <button class="searchstop btn btn-danger form-control" name="but" type="submit" value="2">Стоп</button>
            </div>
        </div>
        <div class="col-xs-12 col-md-5 col-md-offset-1 panel panel-primary">
            <table class="table table-condensed">
                <?= Wall::getStatistics($url) ?>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="tabs">
                    <ul class="nav nav-pills nav-justified">
                        <li class="active"><a href="#tab-1" data-toggle="tab">Альбомы</a></li>
                        <li><a href="#tab-2" data-toggle="tab">Комментарии</a></li>
                    </ul>
                </div>
            </div>

            <div class="panel-body">
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="tab-1">
                        <?
                        $all = 300;
                        $currentValue = (100 * $countwal) / $all;
                        $status = $currentValue > 0 ? $currentValue . ' / 100' : '0 / 100';
                        ?>
                        <h3>Стена</h3>

                        <div class="col-md-12 panel panel-default padding">
                            <div class="col-md-2 col-xs-5">
                                <input class="album-checkbox" type="checkbox" name="wall[]" value="<?= $url ?>" id="wall-check">
                                <label for="wall-check"><img src="/bvk2.png" width="100px" alt="..."></label>
                            </div>
                            <div class="col-md-9 col-xs-7 col-md-offset-1">
                                <label>Стена: </label> <a href="site/SelectWall?gid=<?= $idGroup ?>&url=<?= $url ?>">Стена</a><br>
                                <label>Получено комментариев: </label> <?= $countwal ?><br>
                                <label>Ход выполнения</label>

                                <div class="progress progress-striped active">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="<?= $currentValue ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?= $currentValue ?>%">
                                        <?= round($status, 1) ?>
                                    </div>
                                </div>
                                <a class="btn btn-primary offset col-md-5" name="xls" target="_blank" href="site/exportAlbum?type=walltxt&id=<?= $idGroup ?>">.xls</a>
                                <a class="btn btn-primary offset col-md-5 col-md-offset-2" name="txt" target="_blank" href="site/exportAlbum?type=wallxls&id=<?= $idGroup ?>">.txt</a>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <h3>Альбомы</h3>
                        <? $this->widget('zii.widgets.CListView', array(
                            'dataProvider' => $itemsProvider,
                            'viewData' => array(
                                'url' => $url,
                                'nameGroup' => $nameGroup
                            ),
                            'itemView' => '_group',
                            'summaryText' => 'Показаны альбомы {start} - {end} из {count}',
                            'emptyText' => 'Нет альбомов',
                            'template' => '{sorter}{items}{pager}',
                            'pager' => array(
                                'class' => 'CLinkPager',
                                'header' => '',
                                'maxButtonCount' => 4,
                                'htmlOptions' => array(
                                    'class' => 'pagination'
                                ),
                                'firstPageLabel' => 'Первая',
                                'lastPageLabel' => 'Последняя',
                                'cssFile' => Yii::app()->getRequest()->getBaseUrl(true) . '/assets/index/css/pager.css',
                            ),
                        ));?>
                    </div>
                    <div class="tab-pane fade" id="tab-2">
                        <? $this->widget('zii.widgets.CListView', array(
                            'dataProvider' => $Provider,
                            'summaryText' => 'Показаны комментарии {start} - {end} из {count}',
                            'itemView' => '_table',
                            'emptyText' => 'Комментариев нет',
                            'pager' => array(
                                'class' => 'CLinkPager',
                                'header' => '',
                                'maxButtonCount' => 4,
                                'htmlOptions' => array(
                                    'class' => 'pagination'
                                ),
                                'firstPageLabel' => 'Первая',
                                'lastPageLabel' => 'Последняя',
                                'cssFile' => Yii::app()->getRequest()->getBaseUrl(true) . '/assets/index/css/pager.css',
                            ),
                        ));?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<? $this->endWidget(); ?>
<script type="text/javascript">
    $(document).ready(function () {
        var countWall;
        var url = '<?$urlPage?>'
        var pid = '<?=$pidComment?>';
        if (pid == '') {
            $('button.searchstop').addClass('darkgray');
            $('button.search').removeClass('darkgray');
            $('button.searchstop').attr('disabled', 'disabled');
            $('button.search').removeAttr('disabled', 'disabled');
        } else {
            $('button.searchstop').removeClass('darkgray');
            $('button.search').addClass('darkgray');
            $('button.searchstop').removeAttr('disabled', 'disabled');
            $('button.search').attr('disabled', 'disabled');
        }
        $('button.search').click(function () {
            $.ajax({
                url: '/site/group',
                data: 'type=1'
            })
        })
        $('button.searchstop').click(function () {
            $.ajax({
                url: '/site/group',
                data: 'type=2',
                success: function (data) {

                }
            })
        })
        var stat = setInterval(function () {
            getStat();
        }, 5000);
    })

    function getStat() {
        var match = document.body.innerHTML.match(/value="([\d+]{2,})"/g),
            id = new Array();
        for (var i = 0; i < match.length; i++) {
            id.push(match[i].match(/\d+/)[0]);
        }
        $.ajax({
            url: 'site/stat',
            data: 'album_id=' + id,
            success: function (data) {
                var result = JSON.parse(data);
                for (var key in result) {
                    var val = result[key];
                    var current = Number(val['current']),
                        total = Number(val['total']),
                        comment = Number(val['comment']),
                        percent = Math.round(current * 100 / total);

                    if (current != 0 && total != 0) {
                        if (current == total) id
                        $('div[data-id=' + key + ']').attr('aria-valuenow', percent);
                        $('div[data-id=' + key + ']').css('width', percent + '%');
                        $('div[data-id=' + key + ']').html(percent + '%');
                        $('#countComment' + key).html(comment);
                    }
                }
            }
        })
    }
</script>

protected/views/site/pay.php
<div class="col-md-12">
    <h2>Пополнение баланса</h2>
    <h5>В этом разделе вы можете выбрать удобный для Вас способ пополнения баланса</h5>
    <hr>
    <? $this->widget('zii.widgets.CBreadcrumbs', array(
        'htmlOptions' => array(
            'class' => 'breadcrumb'
        ),
        'homeLink' => '<a href="' . Yii::app()->getRequest()->getBaseUrl(true) . '">Главная</a>',
        'links' => array(
            'Пополнение баланса'
        ),
    )); ?>
    <? $flash = Yii::app()->user->getFlashes(); ?>
    <? if ($flash): ?>
        <? foreach ($flash as $key => $value) : ?>
            <div class="alert alert-<?= $key ?>" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <?= $value ?>
            </div>
        <? endforeach; ?>
    <? endif; ?>
</div>
<div class="col-md-6 col-md-offset-3">
    <?= CHtml::beginForm('', 'get', array('class' => 'text-center')); ?>
    <div class="form-group">
        <?= CHtml::activeRadioButtonList($model, 'type_pay',
            array(
                0 => 'WebMoney',
                1 => 'Yandex Деньги',
                2 => 'Robokassa',
            )
        ) ?>
        </div>
    <div class="form-group">
        <?= CHtml::activeLabel($model, 'sum') ?>
        <?= CHtml::activeTextField($model, 'sum', array('class' => 'form-control')) ?>
    </div>
    <div class="form-group">
        <?= CHtml::submitButton('Оплатить', array('class' => 'btn btn-primary form-control')) ?>
    </div>
    <?= CHtml::endForm(); ?>
</div>
<div class="col-md-12">
    <h2>Купить подписку</h2>
    <h5>Приобретите подписку, чтобы пользоваться услугами сервиса</h5>
    <hr>
</div>

<div class="col-md-3 col-md-offset-2">
    <div class="panel panel-primary text-center no-boder bg-color-orange">
        <div class="panel-body">
            <i class="fa fa-battery-quarter fa-5x"></i>
            <h4>Тестовый период*</h4>
            <h4>20 <i class="fa fa-rub"></i></h4>
        </div>
        <div class="panel-footer back-footer-orange">
            <a type="button" class="btn btn-default btn-circle btn-pay" href="/site/buysubs?type=1">
                <i class="fa fa-check"></i>
            </a>
        </div>
    </div>
</div>
<div class="col-md-2 text-center">
    <h1>ИЛИ</h1>
</div>
<div class="col-md-3">
    <div class="panel panel-primary text-center no-boder bg-color-green">
        <div class="panel-body">
            <i class="fa fa-battery-full fa-5x"></i>
            <h4>Подписка на 1 месяц</h4>
            <h4>500 <i class="fa fa-rub"></i></h4>
        </div>
        <div class="panel-footer back-footer-green">
            <a type="button" class="btn btn-default btn-circle btn-pay" href="/site/buysubs?type=2">
                <i class="fa fa-check"></i>
            </a>
        </div>
    </div>
</div>
<div class="col-md-12">
    <i>* Тестовый период предоставляется всего лишь 1 раз</i>
</div>

protected/views/site/selectgroup.php
<?
Yii::app()->clientScript->registerScript('search',
    "var aid=$aid;
    $(\"select[name='select']\").on('change', function() {
        $.fn.yiiListView.update('list', {
            url: '" . CController::createUrl('site/SelectGroup') . "',
            data: 'type='+$(\"select[name='select']\").val()+'&aid='+aid,
        })
    });");
?>
<? $url = Yii::app()->getRequest()->getParam('url'); ?>
<div class="col-md-12">
    <h2>Комментарии к альбому <?= $nameAlbum ?></h2>
    <!--    <h5>В этом разделе вы можете выбрать удобный для Вас способ пополнения баланса</h5>-->
    <hr>
    <? $this->widget('zii.widgets.CBreadcrumbs', array(
        'htmlOptions' => array(
            'class' => 'breadcrumb'
        ),
        'homeLink' => '<a href="' . Yii::app()->getRequest()->getBaseUrl(true) . '">Главная</a>',
        'links' => array(
            'Альбомы группы ' => array('/site/group', 'url' => $url),
            'Комментарии к альбому ' . $nameAlbum
        ),
    )); ?>
</div>
</div>
<form>
    <input type="hidden" name='aid' value='<?= $aid ?>'>
    <? if (Yii::app()->user->hasFlash('error')) { ?>
        <center><p><span style="font-size:20px"><strong>
                        <?= Yii::app()->user->getFlash('error'); ?>
                    </strong></span></p></center>
    <? } else { ?>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-2 offset">
                                <input name="textfield" type="text" class="form-control" placeholder="Введите текст поиска">
                            </div>
                            <div class="col-md-2 offset">
                                <button class="btn btn-primary form-control search" name="but" class="btn btn-primary btn-lg" value="1">Поиск</button>
                            </div>
                            <div class="col-md-2 offset">
                                <select name="select" class="form-control">
                                    <option value="0">Показать всё</option>
                                    <option value="1">Показать спам</option>
                                    <option value="2">Показать прочитнные</option>
                                    <option value="3">Показать отмеченные</option>
                                </select>
                            </div>
                            <div class="col-md-2 offset">
                                <select name="metka" class="form-control">
                                    <option value="metka-spam">Отметить как спам</option>
                                    <option value="metka-read">Отметить как прочитнные</option>
                                    <option value="metka-select">Отметить как отмеченные</option>
                                </select>
                            </div>
                            <div class="col-md-2 offset">
                                <button class="btn btn-primary form-control search" name="but" type="submit" class="btn btn-primary btn-lg" value="2">Отметить</button>
                            </div>
                            <div class="col-md-2 offset">
                                <button class="btn btn-primary form-control search" name="but" class="btn btn-primary btn-lg" value="3">Удалить</button>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <?
                        if (isset($dataProvider)) {
                            $this->renderPartial('list', array('dataProvider' => $dataProvider), false, true);
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    <? } ?>
</form>